story6/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('tdd/', index),
    
]

story9/urls.py
from django.urls import path, include
from .views import *
from django.contrib import admin 
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


app_name = "story9"
urlpatterns = [
    path('', search_book, name="listbook"),
    path('tambah', tambah, name="tambah"),
	path('kurang', kurang, name="kurang"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

storytdd/urls.py
from django.conf.urls import include, url
from django.urls import re_path
from django.contrib import admin
import story6.urls as story6
from .views import logoutPage
from django.contrib.auth import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^story6/',include(('story6.urls', 'story6'), namespace = 'story6')),
	url(r'^story9/',include(('story9.urls', 'story9'), namespace = 'story9')),
	url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^logout/',logoutPage, name='logout'),
]

story6/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Status(models.Model):
    date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=300)

story9/models.py
from django.db import models

# Create your models here.

story6/forms.py
from django import forms

from .models import Status

# class Date(forms.DateTimeInput):
#     input_type = 'datetime-local'

class StatusForm(forms.ModelForm):

    class Meta:
        model = Status
        fields = ('status',)

story9/forms.py
from django import forms


class SearchForm(forms.Form):
    search_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Search book',
    }
    title = forms.CharField(max_length = 300, label='', widget=forms.TextInput(attrs=search_attrs))

story6/views.py
from django.shortcuts import render
from .forms import StatusForm
from .models import Status

# Create your views here.
def index(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if form.is_valid():
            new_status = form.save()
            new_status.save()
    form = StatusForm()
    statusss = Status.objects.all().values()
    return render(request,'hw.html', {'form': form, 'statuss': statusss})

story9/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.core import serializers
from .forms import SearchForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
import requests
import json


import requests
import json
#Create your views here.
def search_book(request):
    response = {}
    response['form'] = SearchForm()

    response['data'] = None
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            search = cd['title']
            URL = "https://www.googleapis.com/books/v1/volumes?q=" + search
            get_json = requests.get(URL).json()
            json_dict = json.dumps(get_json)
            response['data'] = json_dict

        return render(request, "listbook.html", response)
    else:
        return render(request, "listbook.html", response)

def tambah(request):
	print(dict(request.session))
	request.session['counter'] = request.session['counter'] + 1
	return HttpResponse(request.session['counter'], content_type = "application/json")

def kurang(request):

	request.session['counter'] = request.session['counter'] - 1
	return HttpResponse(request.session['counter'], content_type = "application/json")




# def logout_view(request):
#     logout(request)
#     return HttpResponseRedirect('/books')

storytdd/views.py
from django.contrib.auth import logout
from django.http import HttpResponseRedirect


def logoutPage(request):
	request.session.flush()
	logout(request)
	return HttpResponseRedirect('/books')

story6/templates/hw.html
<!DOCTYPE html>
<html>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


<title>My Status</title>

<body style="background-color:rgba(176, 224, 230, 1)">

<h1>Hello, Apa kabar?</h1>

<div class = "row">
    <div class="col-md-3">
    <form method="POST">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Submit</button>
        </form>
    </div>
    <div class="col-md-8">
        <img id="fotoku" src="https://lh3.googleusercontent.com/EMmEGWZ1KpDQEg1xNNf7vgmsg803G9qaXG_KVt6994FIE85X28V-ug1VyiM7shUvYJZQX_awYyEfcHAw526e0-1XEi5rbcg-roWdhnWa4zeXgdiSUj4GdUt9PLiNWqaQ3zPN1EagutNT6-64GRDqbmW1aRpa4j72RrZVE00_OphtS-F9sWhaRyWtbz4qjz8syqCVzm57Sw6EfKV8GyyFYNPULgvOJdsCgZeQbWVDz8aN_Rn5FtNlcyGmnsCbk2-LmOuXIHOEgHFsOanqVgLdnN51Bx5EfC7x4RGHtCNxMgRkpxCpW_PVzW7VqW8qhHwUGTIjF9fs4xksIcD6I1S2RcOKO2K0U1xlIGoHc9jP5GMMKSdWCfQlgv_jbCbTryU_rdFBd1aIfvi4-MROthtxJ42i82EXuQVQkgm71K9pv4_vmHaUtnf-SrB-6nVJlRk7NN9tvskFFNbINfrYA5KuTbPyygS6n63Ma8SyEyKgs4AwHMCmbtk1cd7gp5NuoOmUM_bO12B0vVjov5dXW3zhzareS518NOzIXcGzW_UDtYP_67-KxRj8WkoLJDbiRdiTYDg9vnf3j1QK3NMcYIEnC6ls06oh-x4fVIP1UpMWMs_vn9pUWdMIsblYkGZjTd0=w720-h480-no" class="img-rounded" alt="Cinque Terre" width="50%">
        <h1>Faza Siti Sabira Prakoso</h1>
        <h3>NPM: 1706023334</h3>
        <h3>Universitas Indonesia</h3>
    </div>
</div>





<div class = "row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        {% for status in statuss %}
        <div>
            <p>Status: {{ status.status }}</p>
            <p>Date: {{ status.date }}</p>
        </div>
        <br>
    {% endfor %}
    </div>
    
</div>

</body>
</html>

story9/templates/listbook.html
{%load static%}
{%load staticfiles%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <title>List of Book</title>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    </head>
    <body>
        {% if user.is_authenticated %}
		<div class="text-right" style="font-family: 'Signika', sans-serif; padding-right: 50px;">
			<br>
			<h3>Welcome, {{ user.username }}!</h3>
			<button class="btn btn-danger"><a href="{% url 'logout' %}" style="color: white">Logout</a></button>
		</div>
	{% else %}
	<div class="text-right" style="font-family: 'Signika', sans-serif; padding-right: 50px;">
		<br>
		<button class="btn btn-danger"><a href="{% url 'social:begin' 'google-oauth2' %}" style="color: white">Login with Google</a></button>
		<br>
	</div>
	{% endif %}

        <header><i id = "count" class="fas fa-star"></i></header>
        <div class="container">
            <div class="row">
                <h1>Search Book</h1>
                <div class="col-md-12">
                    <div class="text-center">
                        <form id="listbook" method="POST" action= "{% url 'story9:listbook'%}">
                            {% csrf_token %}
                            {{form}}
                            <button class="btn btn-warning">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <table id = "res" class="table table-stripped">
                        
                    </table>
                </div>
            </div>
        </div>
        {%if data%}
        <script>
            var res = JSON.parse("{{data|escapejs}}");
            $("#res").append("<thead><tr><th scope=\"col\">No</th><th scope=\"col\">Favorite</th><th scope=\"col\">Book</th><th scope=\"col\">Title</th><th scope=\"col\">Author</th></tr></thead><tbody>");
            for (i=0; i<res.items.length; i++) {
                var judult = "<td class=\"judul\">" + res.items[i].volumeInfo.title + "</td>";
                var authort = "<td class=\"author\">"+ res.items[i].volumeInfo.authors + "</td>";
                var nomor = "<tr id=\"item-"+ i+1 + "\">";
                var roww = "<th scope="+ "\"row\">" + (i+1) + "</th>";
                var star = "<td><i title=\"Favorite\" class=\"fav far fa-star\"></td>"
                var link = "<td><a target=\"_blank\" href=\""+ res.items[i].volumeInfo.infoLink + "\">"+ "<img src=\"" + res.items[i].volumeInfo.imageLinks.thumbnail + "\">" + "</a></td>"
                $("#res").append(nomor + roww + star + link + judult + authort + "</tr>");
                }
                $("#res").append("</tbody>");
            
        </script>
        {%endif%}
        <script src="{%static 'listbook.js'%}"></script>

        <script src="{%static 'listbook.js'%}"></script>
	<script>
		$('#google-button').on('click', function() {
		  // Initialize with your OAuth.io app public key
		  OAuth.initialize('840738897991-9h9inql5gdqsocclp0a6ehhqk5k09kbk.apps.googleusercontent.com');
		  // Use popup for oauth
		  OAuth.popup('google').then(google => {
		    console.log('google:',google);
		    // Retrieves user data from oauth provider
		    // Prompts 'welcome' message with User's email on successful login
		    // #me() is a convenient method to retrieve user data without requiring you
		    // to know which OAuth provider url to call
		    google.me().then(data => {
		      console.log('me data:', data);
		      alert('Google says your email is:' + data.email + ".\nView browser 'Console Log' for more details");
		    });
		    // Retrieves user data from OAuth provider by using #get() and
		    // OAuth provider url
		    google.get('/plus/v1/people/me').then(data => {
		      console.log('self data:', data);
		    })
		  });
		})
	</script>

    </body>
</html>